arrowParens: avoid
bracketSpacing: false
# endOfLine: lf
# htmlWhitespaceSensitivity: css
insertPragma: true
# parser: babel
printWidth: 120
proseWrap: never
quoteProps: as-needed
requirePragma: true
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: true
