version: '3'
services:

  consulta_cep:
    container_name: dev
    build: ./
    command: node index.js
    environment:
      DEBUG: cep-api:*
      NODE_ENV: dev
      PORT: 3000
      RPORT: 6379
      RHOST: redis
    ports:
      - 3001:3000
    volumes:
      - ./app:/home/node/consulta-cep/app
    networks:
      - app-tier

  redis:
    image: redis:alpine
    ports: 
      - 6379:6379
    volumes:
      - db-data:/data
    networks:
      - app-tier

volumes:
  db-data:

networks:
  app-tier:

# docker-compose -f docker-compose.dev.yml up --build -d
