# entr
FROM lagden/entr:4.6-alpine3.12 as entr

LABEL autodelete="true"
LABEL maintainer="docker@lagden.in"

# APP Dev
FROM node:14.15-alpine3.12

LABEL maintainer="docker@lagden.in"

## If Docker Host is Mac or Windows
ARG ARG_ENTR_INOTIFY_WORKAROUND=1
ENV ENTR_INOTIFY_WORKAROUND=$ARG_ENTR_INOTIFY_WORKAROUND

ARG NODE_ENV="production"
ARG BASE="/home/node"

ENV NODE_ENV=$NODE_ENV
ENV BASE=$BASE
ENV BASE_APP=$BASE/app

WORKDIR /usr/local/bin
COPY --from=entr /usr/local/bin/entr .

WORKDIR $BASE

ADD --chown=node:node . $BASE_APP

WORKDIR $BASE_APP

RUN npm ci --ignore-scripts

USER node
