version: "3.7"
services:
  app:
    image: ${REGISTRY}/${IMAGE}:${VERSION}
    command: ["node", "server"]
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      PORT_PUBLISHED: ${PORT_PUBLISHED}
      DEBUG: ${DEBUG}
      DEBUG_PREFIX: ${DEBUG_PREFIX}
      DEBUG_COLORS: ${DEBUG_COLORS}
      DEBUG_HIDE_DATE: ${DEBUG_HIDE_DATE}
      VERSION: ${VERSION}
    ports:
      - ${PORT_PUBLISHED}:${PORT}
    volumes:
      - api_data:/home/node/app/data
    networks:
      - net
    deploy:
      replicas: ${DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: ${DEPLOY_RESOURCES_LIMITS_CPUS}
          memory: ${DEPLOY_RESOURCES_LIMITS_MEMORY}
        reservations:
          cpus: ${DEPLOY_RESERVATIONS_LIMITS_CPUS}
          memory: ${DEPLOY_RESERVATIONS_LIMITS_MEMORY}
      restart_policy:
        condition: on-failure

networks:
  net:
    name: ${NETWORK_NAME}

volumes:
  api_data:
    name: ${VOL_NAME}_db
