version: "3.7"
services:
  app:
    command: >
      /bin/ash -c "
        npm test
      "
    volumes:
      - ./test:/home/node/app/test
    environment:
      - NODE_ENV=development
      - APP_ENV=test
