version: "3.6"
services:
  sut:
    build:
      context: ./
      args:
        NODE_ENV: development
        VERSION: test
    command: ["npm", "test"]
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
