version: "3.6"
services:
  sut:
    build:
      context: ./
      args:
        NODE_ENV: development
        VERSION: test
    command: ["npm", "test"]
    volumes:
      - ./server:/home/node/app/server
      - ./test:/home/node/app/test
    environment:
      - NODE_ENV=development
      - APP_ENV=test
