version: "3.7"
services:
  cep:
    build:
      context: ./
      args:
        PORT: ${PORT}
        NODE_ENV: ${NODE_ENV}
        VERSION: ${VERSION}
    command: ["npm", "start"]
    volumes:
      - ./server:/home/node/app/server
      - ./test:/home/node/app/test
