version: "3.7"
services:
  app:
    image: ${REGISTRY}/${IMAGE}:${VERSION}
    command: ["node", "server"]
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      PORT_PUBLISHED: ${PORT_PUBLISHED}
      DEBUG: ${DEBUG}
      DEBUG_PREFIX: ${DEBUG_PREFIX}
      DEBUG_COLORS: ${DEBUG_COLORS}
      DEBUG_HIDE_DATE: ${DEBUG_HIDE_DATE}
      VERSION: ${VERSION}
    ports:
      - ${PORT_PUBLISHED}:${PORT}
    volumes:
      - api_data:/home/node/app/data

volumes:
  api_data:
    name: ${VOL_NAME}_api
