version: '3.6'
services:
  dev:
    build:
      context: ./
      args:
        port: ${PORT}
        npm_cmd: "npm i --progress=false --quiet"
    image: cepkoa:dev
    command: ["npm", "start"]
    environment:
      - DEBUG=${PREFIX_DEBUG}:*
      - NODE_ENV=dev
      - RHOST=redis
    ports:
      - 1235:${PORT}
    volumes:
      - ./src:/home/node/app/src
    networks:
      - net
    depends_on:
      - redis

  redis:
    image: redis:4.0.5-alpine
    hostname: redis
    networks:
      - net

  test:
    image: cepkoa:dev
    container_name: test
    command: ["npm", "test"]
    environment:
      - NODE_ENV=test
      - RHOST=redis
    volumes:
      - ./test:/home/node/app/test
      - ./src:/home/node/app/src
    networks:
      - net
    depends_on:
      - dev
      - redis

networks:
  net:
