version: "3.6"
services:
  redis:
    image: redis:5-alpine
    command: >
      --appendonly yes
    networks:
      - net

  sut:
    build:
      context: ./
      args:
        PORT: 3000
        NODE_ENV: test
        VERSION: test
    command: ["npm", "test"]
    volumes:
      - ./src:/home/node/app/src
      - ./test:/home/node/app/test
    environment:
      - NODE_ENV=test
      - REDIS=redis:6379
    networks:
      - net
    depends_on:
      - redis

networks:
  net:
