version: "3.7"
services:
  app:
    build:
      context: ./
      target: dev
      args:
        NODE_ENV: ${NODE_ENV}
    command: >
      /bin/ash -c "
        bin/helper/wait ${REDIS_HOST}:${REDIS_PORT};
        bin/docker/watch
      "
    environment:
      WATCH_CMD: "${WATCH_CMD}"
      HOSTNAME_CUSTOM: "${HOSTNAME_CUSTOM}"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.yarn
