version: "3.7"
services:
  app:
    tty: true
    build:
      dockerfile: ${DOCKERFILE}
      context: ./
      args:
        NODE_ENV: ${NODE_ENV}
        ARG_ENTR_INOTIFY_WORKAROUND: ${ARG_ENTR_INOTIFY_WORKAROUND:-1}
    # depends_on:
    #   - seu_db_ou_dependencia
    command: >
      /bin/ash -c "
        bin/watch
      "
    environment:
      WATCH_FOLDERS: "${WATCH_FOLDERS}"
      WATCH_CMD: "${WATCH_CMD}"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
