version: "3.7"
services:
  app:
    build:
      dockerfile: ${DOCKERFILE}
      context: ./
      args:
        NODE_ENV: ${NODE_ENV}
        VERSION: ${VERSION}
        ARG_ENTR_INOTIFY_WORKAROUND: ${ARG_ENTR_INOTIFY_WORKAROUND:-0}
    command: >
      /bin/ash -c "
        bin/watch
      "
    environment:
      WATCH_FOLDERS: "${WATCH_FOLDERS}"
      WATCH_CMD: "${WATCH_CMD}"
    volumes:
      - ./server:/home/node/app/server
      - ./test:/home/node/app/test
