version: "3.7"
services:
  cep:
    image: ${REGISTRY}/${IMAGE}:${VERSION}
    command: ["node", "server"]
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DEBUG_COLORS=1
      - DEBUG=${DEBUG}
      - DEBUG_PREFIX=${DEBUG_PREFIX}
      - VERSION=${VERSION}
    ports:
      - ${PORT_PUBLISHED}:${PORT}
