version: '3.6'
services:
  dev:
    build:
      context: ./
      args:
        NODE_ENV: dev
        PORT: ${PORT:-3000}
    image: cepkoa:dev
    container_name: dev
    command: ["npm", "start"]
    env_file:
     - ./.env
    environment:
      - NODE_ENV=dev
      - DEBUG_COLORS=1
      - DEBUG=cepkoa:*
      - RHOST=redis
    ports:
      - ${LOCALPORT:-3333}:${PORT:-3000}
    volumes:
      - ./src:/home/node/app/src
      - ./index.js:/home/node/app/index.js
    networks:
      - net
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    hostname: redis
    networks:
      - net

  test:
    build:
      context: ./
      args:
        NODE_ENV: test
        PORT: ${PORT:-3000}
    image: cepkoa:test
    container_name: test
    command: ["npm", "test"]
    env_file:
     - ./.env
    environment:
      - NODE_ENV=test
      - RHOST=redis
    volumes:
      - ./test:/home/node/app/test
      - ./src:/home/node/app/src
      - ./index.js:/home/node/app/index.js
    networks:
      - net
    depends_on:
      - redis

networks:
  net:
