version: "3.6"
services:
  sut:
    build:
      context: ./
      args:
        NODE_ENV: development
        VERSION: test
    command: ["npm", "test"]
    volumes:
      - api_data:/home/node/app/data

volumes:
  api_data:
    name: cepkoa_vol_test_db
