version: '3'
services:
  test:
    build:
      context: ./
      args:
        npm_cmd: "npm i --progress=false --quiet"
    command: ["npm", "test"]
    environment:
      - NODE_ENV=test
      - RHOST=redis
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - redis-net
    depends_on:
      - redis

  redis:
    image: redis:4.0.5-alpine
    hostname: redis
    networks:
      - redis-net

networks:
  redis-net:

volumes:
  node_modules:

## to run
# docker-compose -f docker-compose.test.yml run test

## to build
# docker-compose -f docker-compose.test.yml up --build -d
