version: '3'
services:
  app:
    image: lagden/cep_consulta:5.0.0
    command: ["node", "index.js"]
    environment:
      - DEBUG=${PREFIX_DEBUG}:error
      - NODE_ENV=production
      - RHOST=redis
    ports:
      - 1235:${PORT}
    networks:
      - redis-net
    depends_on:
      - redis

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: always
    networks:
      - redis-net
    volumes:
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data:

# docker-compose up --build -d
