version: '3'
services:
  consulta_cep:
    container_name: dev
    build:
      context: ./
      dockerfile: Dockerfile
    command: node index.js
    environment:
      DEBUG: cep-api:*
      NODE_ENV: dev
      PORT: 3000
    ports:
      - 3001:3000
    volumes:
      - ./app:/home/node/consulta-cep/app
      - db-data:/home/node/consulta-cep/data

volumes:
  db-data:

# docker-compose -f docker-compose.dev.yml up --build -d
