version: "3.6"
services:
  redis:
    image: redis:6-alpine
    command: >
      --appendonly yes
    networks:
      - net

  sut:
    build:
      context: ./
      target: dev
      args:
        NODE_ENV: development
        VERSION: test
    command: >
      /bin/ash -c "
        bin/helper/wait ${REDIS_HOST}:${REDIS_PORT};
        bin/docker/watch
      "
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.yarn
